### ISSUE TITLE
Source code availability 

### ISSUE THREAD

**Issue by AlexanderViand-Intel** [corelab-src/elasm#1]
Hi @corelab-src 👋 

in [the paper](https://www.usenix.org/system/files/sec23fall-prepub-147-lee-yongwoo.pdf), you mention that "The source code of ELASM compiler will be publicly available on https://github.com/corelab-src/elasm."
With the conference being in less than two weeks, I'm wondering if you've got a more concrete timeline on this? 

Looking forward to seeing (some of?) you in Anaheim! 
Alex

**Comment by rovelace** [comment]
Hi @AlexanderViand-Intel, 

I will upload the source code on Monday if there is no remaining issue. 
Thank you for your interest. 

I found that your presentation is back-to-back with my presentation!
Looking forward to seeing you, too! 
Yongwoo
