### ISSUE TITLE
Supporting for bootstrapping

### ISSUE THREAD

**Issue by JinkaiZhang-commits** [corelab-src/elasm#2]
Hello, I am very interested in elasm compiler project! I noticed that the elasm compiler does not seem to take the bootstrapping step into account in the optimization process. Is adding the bootstrapping step automatically a future feature of the elasm compiler?

**Comment by JinkaiZhang-commits** [comment]
Thanks for your reply. I look forward to your update. :)

**Comment by AlexanderViand-Intel** [comment]
Hey all, since it's been a while, I wanted to check back in to see what the status of DaCapo/Automated Bootstrapping open sourcing is :)
